import os
import shutil
import subprocess
from typing import List, Optional, Tuple


def get_default_interface() -> Optional[str]:
    try:
        res = subprocess.run(
            ["ip", "route", "show", "default"],
            capture_output=True,
            text=True,
            check=True,
        )
        tokens = res.stdout.split()
        if "dev" in tokens:
            return tokens[tokens.index("dev") + 1]
    except Exception:
        pass
    return None


def get_current_dns() -> List[str]:
    iface = get_default_interface()
    
    if shutil.which("resolvectl") and iface:
        try:
            res = subprocess.run(
                ["resolvectl", "dns", iface],
                capture_output=True,
                text=True,
                check=True,
            )
            parts = res.stdout.split(":")
            if len(parts) > 1:
                servers = parts[1].strip().split()
                if servers:
                    return servers
        except subprocess.SubprocessError:
            pass

    nameservers: List[str] = []
    if os.path.exists("/etc/resolv.conf"):
        try:
            with open("/etc/resolv.conf", "r") as f:
                for line in f:
                    line = line.strip()
                    if line.startswith("nameserver"):
                        parts = line.split()
                        if len(parts) > 1:
                            nameservers.append(parts[1])
        except IOError:
            pass

    return nameservers


def apply_linux_dns(primary: str, fallback: str = "1.1.1.1") -> Tuple[bool, str]:
    iface = get_default_interface()

    if shutil.which("resolvectl") and iface:
        try:
            subprocess.run(
                ["resolvectl", "dns", iface, primary, fallback],
                check=True,
                capture_output=True,
                text=True,
            )
            subprocess.run(
                ["resolvectl", "flush-caches"],
                check=True,
                capture_output=True,
                text=True,
            )
            return True, f"Updated DNS via resolvectl on interface '{iface}'"
        except subprocess.CalledProcessError as exc:
            err = exc.stderr.strip() if exc.stderr else str(exc)
            pass

    try:
        content = (
            "# Generated by Flashy-DNS v2\n"
            f"nameserver {primary}\n"
            f"nameserver {fallback}\n"
            "options timeout:2 attempts:2\n"
        )
        with open("/etc/resolv.conf", "w") as f:
            f.write(content)
        return True, "Updated DNS directly via /etc/resolv.conf"
    except PermissionError:
        return False, "Permission denied writing to /etc/resolv.conf (requires sudo / CAP_NET_ADMIN)"
    except Exception as exc:
        return False, f"Failed to update DNS: {exc}"
